// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpopzjorqhcmdfteaxhg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdwb3B6am9ycWhjbWRmdGVheGhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5OTkzMzcsImV4cCI6MjA2MDU3NTMzN30.9HKqInPNA7BaFZ_-4GOHKj1LteEWmPRtdlclADxxoRA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);